# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
# create foods
Food.create(name: "Apple", kcal_per_g: 0.37)
Food.create(name: "Apricot", kcal_per_g: 0.34)
Food.create(name: "Avocado", kcal_per_g: 1.34)
Food.create(name: "Banana", kcal_per_g: 0.51)
Food.create(name: "Blackberries", kcal_per_g: 0.21)
Food.create(name: "Blackcurrant", kcal_per_g: 0.24)
Food.create(name: "Cherries", kcal_per_g: 0.36)
Food.create(name: "Clementine", kcal_per_g: 0.39)
Food.create(name: "Coconut (Fresh)", kcal_per_g: 3.51)
Food.create(name: "Cranberries", kcal_per_g: 0.15)
Food.create(name: "Cucumber", kcal_per_g: 0.15)
Food.create(name: "Dates (Dried)", kcal_per_g: 2.27)
Food.create(name: "Figs (Fresh)", kcal_per_g: 2.09)
Food.create(name: "Grapefruit", kcal_per_g: 0.25)
Food.create(name: "Kiwi", kcal_per_g: 0.42)
Food.create(name: "Lemon", kcal_per_g: 0.15)
Food.create(name: "Lime", kcal_per_g: 0.09)
Food.create(name: "Lychee", kcal_per_g: 0.36)
Food.create(name: "Mango", kcal_per_g: 0.39)
Food.create(name: "Acorn squash", kcal_per_g: 0.4)
Food.create(name: "Artichoke", kcal_per_g: 0.41)
Food.create(name: "Asparagus", kcal_per_g: 0.29)
Food.create(name: "Beetroot", kcal_per_g: 0.42)
Food.create(name: "Broccoli", kcal_per_g: 0.35)
Food.create(name: "Brussels Sprout", kcal_per_g: 0.51)
Food.create(name: "Butternut squash", kcal_per_g: 0.36)
Food.create(name: "Cabbage", kcal_per_g: 0.27)
Food.create(name: "Carrot", kcal_per_g: 0.1)
Food.create(name: "Cauliflower", kcal_per_g: 0.3)
Food.create(name: "Celery", kcal_per_g: 0.08)
Food.create(name: "Chicory", kcal_per_g: 0.11)
Food.create(name: "Corn", kcal_per_g: 0.54)
Food.create(name: "Edamame", kcal_per_g: 1.4)
Food.create(name: "Green beans", kcal_per_g: 0.25)
Food.create(name: "Iceberg lettuce", kcal_per_g: 0.1)
Food.create(name: "Kale", kcal_per_g: 0.3)
Food.create(name: "Leek", kcal_per_g: 0.2)
Food.create(name: "Mushroom", kcal_per_g: 0.08)
Food.create(name: "Onion", kcal_per_g: 0.43)
Food.create(name: "Peas", kcal_per_g: 0.7)
Food.create(name: "Peppers (Red)", kcal_per_g: 0.21)
Food.create(name: "Potato", kcal_per_g: 0.97)
Food.create(name: "Pumpkin", kcal_per_g: 0.13)
Food.create(name: "Radish", kcal_per_g: 0.33)
Food.create(name: "Romaine Lettuce", kcal_per_g: 0.15)
Food.create(name: "Spinach", kcal_per_g: 0.24)
Food.create(name: "Bean Sprouts", kcal_per_g: 0.3)
Food.create(name: "Turnips", kcal_per_g: 0.23)
Food.create(name: "Yam", kcal_per_g: 1.53)
Food.create(name: "Zucchini / Courgette", kcal_per_g: 0.1)
Food.create(name: "Adzuki Beans", kcal_per_g: 0.146)
Food.create(name: "Amaranth (Dried)", kcal_per_g: 0.359)
Food.create(name: "Barley (Dried)", kcal_per_g: 0.31)
Food.create(name: "Beluga Lentils", kcal_per_g: 0.094)
Food.create(name: "Black Beans", kcal_per_g: 0.12)
Food.create(name: "Black Eyed Peas", kcal_per_g: 0.11)
Food.create(name: "Brown Lentils", kcal_per_g: 0.105)
Food.create(name: "Brown Rice", kcal_per_g: 0.132)
Food.create(name: "Buckwheat", kcal_per_g: 0.075)
Food.create(name: "Bulgur", kcal_per_g: 0.085)
Food.create(name: "Chickpeas", kcal_per_g: 0.128)
Food.create(name: "Corn", kcal_per_g: 0.054)
Food.create(name: "Green Lentils", kcal_per_g: 0.105)
Food.create(name: "Green Peas", kcal_per_g: 0.07)
Food.create(name: "Green Split Peas", kcal_per_g: 0.122)
Food.create(name: "Large Fava Beans", kcal_per_g: 0.124)
Food.create(name: "Millet", kcal_per_g: 0.199)
Food.create(name: "Oats (Rolled)", kcal_per_g: 0.381)
Food.create(name: "Pinto Beans", kcal_per_g: 0.137)
Food.create(name: "Quinoa", kcal_per_g: 0.111)
Food.create(name: "Red Kidney Beans", kcal_per_g: 0.105)
Food.create(name: "Red Split Lentils", kcal_per_g: 0.1)
Food.create(name: "White Rice", kcal_per_g: 0.131)
Food.create(name: "Wild Rice", kcal_per_g: 0.15)
Food.create(name: "Bacon (Pork)", kcal_per_g: 2.4)
Food.create(name: "Chicken Breast", kcal_per_g: 1.48)
Food.create(name: "Chicken Wings", kcal_per_g: 1.1)
Food.create(name: "Chicken Thighs", kcal_per_g: 1.33)
Food.create(name: "Chicken Eggs", kcal_per_g: 1.55)
Food.create(name: "Duck (No Skin)", kcal_per_g: 1.95)
Food.create(name: "Escargots", kcal_per_g: 0.9)
Food.create(name: "Lamb", kcal_per_g: 1.22)
Food.create(name: "Liver", kcal_per_g: 1.19)
Food.create(name: "Sausage (Chicken)", kcal_per_g: 1.72)
Food.create(name: "Sausage (Turkey)", kcal_per_g: 1.96)
Food.create(name: "Sausage (Pork)", kcal_per_g: 3.18)
Food.create(name: "Quail Eggs", kcal_per_g: 1.58)
Food.create(name: "Turkey (Dark Meat)", kcal_per_g: 1.84)
Food.create(name: "Turkey (White Meat)", kcal_per_g: 1.04)
Food.create(name: "Quail Eggs", kcal_per_g: 1.58)

Food.create(name: "Venison", kcal_per_g: 1.34)
Food.create(name: "Ahi Tuna", kcal_per_g: 120)
Food.create(name: "Albacore", kcal_per_g: 128)
Food.create(name: "Catfish", kcal_per_g: 95)
Food.create(name: "Caviar", kcal_per_g: 250)
Food.create(name: "Crab", kcal_per_g: 87)
Food.create(name: "Eel", kcal_per_g: 184)
Food.create(name: "Flounder", kcal_per_g: 91)
Food.create(name: "Grouper", kcal_per_g: 92)
Food.create(name: "Herring", kcal_per_g: 158)
Food.create(name: "Lobster", kcal_per_g: 90)
Food.create(name: "Mussels", kcal_per_g: 86)
Food.create(name: "Oysters", kcal_per_g: 81)
Food.create(name: "Salmon", kcal_per_g: 183)
Food.create(name: "Scallops", kcal_per_g: 88)
Food.create(name: "Sea Bass", kcal_per_g: 97)
Food.create(name: "Shrimp", kcal_per_g: 106)
Food.create(name: "Smelt", kcal_per_g: 97)
Food.create(name: "Squid", kcal_per_g: 92)
Food.create(name: "Tilapia", kcal_per_g: 96)
Food.create(name: "Trout", kcal_per_g: 148)
Food.create(name: "Whitefish", kcal_per_g: 134)
Food.create(name: "Yellowfin Tuna", kcal_per_g: 108)
Food.create(name: "Butter", kcal_per_g: 7.16)
Food.create(name: "Buttermilk (1%)", kcal_per_g: 0.41)
Food.create(name: "Cheddar Cheese", kcal_per_g: 4.03)
Food.create(name: "Cottage Cheese (1%)", kcal_per_g: 0.72)
Food.create(name: "Cream (heavy)", kcal_per_g: 3.47)
Food.create(name: "Cream Cheese", kcal_per_g: 2.31)
Food.create(name: "Evaporated Milk", kcal_per_g: 1.42)
Food.create(name: "Ghee", kcal_per_g: 8.99)
Food.create(name: "Goat's Milk", kcal_per_g: 0.71)
Food.create(name: "Ice Cream (Vanilla)", kcal_per_g: 2.07)
Food.create(name: "Kefir", kcal_per_g: 0.67)
Food.create(name: "Ricotta Cheese", kcal_per_g: 1.74)
Food.create(name: "Skim Milk", kcal_per_g: 0.38)
Food.create(name: "Sour Cream", kcal_per_g: 2.14)
Food.create(name: "Soy Milk", kcal_per_g: 0.46)
Food.create(name: "Swiss Cheese", kcal_per_g: 3.80)
Food.create(name: "Yogurt, Whole Milk", kcal_per_g: 0.61)
Food.create(name: "Quail Eggs", kcal_per_g: 1.58)
Food.create(name: "Yogurt, no fat", kcal_per_g: 55)
Food.create(name: "Whole Milk", kcal_per_g: 62)
Food.create(name: "Bagel", kcal_per_g: 275)
Food.create(name: "Biscuit", kcal_per_g: 300)
Food.create(name: "Corn tortilla", kcal_per_g: 218)
Food.create(name: "English Muffin", kcal_per_g: 235)
Food.create(name: "Flour tortilla", kcal_per_g: 312)
Food.create(name: "Pasta (cooked)", kcal_per_g: 158)
Food.create(name: "Rye Bread", kcal_per_g: 258)
Food.create(name: "Sourdough Bread", kcal_per_g: 266)
Food.create(name: "Wheat Bread", kcal_per_g: 313)
Food.create(name: "Whole grain pasta (cooked)", kcal_per_g: 124)

Food.create(name: "Avocado oil", kcal_per_g: 883)
Food.create(name: "Canola oil", kcal_per_g: 883)
Food.create(name: "Coconut oil", kcal_per_g: 861)
Food.create(name: "Corn oil", kcal_per_g: 857)
Food.create(name: "Olive oil", kcal_per_g: 880)
Food.create(name: "Peanut oil", kcal_per_g: 883)
Food.create(name: "Safflower oil", kcal_per_g: 883)
Food.create(name: "Soybean oil", kcal_per_g: 883)
Food.create(name: "Sunflower oil", kcal_per_g: 883)
Food.create(name: "Carbonated Cola", kcal_per_g: 37)
Food.create(name: "Coffee, black", kcal_per_g: 1)
Food.create(name: "Diet Cola", kcal_per_g: 0)
Food.create(name: "Apple Juice (100%)", kcal_per_g: 49)
Food.create(name: "Ginger ale", kcal_per_g: 34)
Food.create(name: "Hot Cocoa", kcal_per_g: 81)
Food.create(name: "Hot Tea (no sugar)", kcal_per_g: 1)
Food.create(name: "Iced Tea (no sugar)", kcal_per_g: 1)
Food.create(name: "Lemonade", kcal_per_g: 25)
Food.create(name: "Sweet Iced Tea", kcal_per_g: 18)
Food.create(name: "Tonic Water", kcal_per_g: 35)

Food.create(name: "Light Beer", kcal_per_g: 29)
Food.create(name: "Gin", kcal_per_g: 217)
Food.create(name: "Lager", kcal_per_g: 43)
Food.create(name: "Pilsner", kcal_per_g: 44)
Food.create(name: "Porter", kcal_per_g: 45)
Food.create(name: "Rum", kcal_per_g: 217)
Food.create(name: "Stout", kcal_per_g: 50)
Food.create(name: "Vodka", kcal_per_g: 217)
Food.create(name: "Whiskey", kcal_per_g: 217)
Food.create(name: "Wine", kcal_per_g: 83)

# Users
User.create(
    username: "user1",
    firstname: "John",
    lastname: "Doe",
    age: "30",
    email: "user1@example.com",
    weight: 70,
    height: 170,
    password: "password",
    password_confirmation: "password"
  )
  
User.create(username: "jane_smith", firstname: "Jane", lastname: "Smith", age: "25", email: "jane_smith@example.com", weight: 65, height: 165, password: "password", password_confirmation: "password")


# Goals
Goal.create(user_id: 1, target_weight: 70, goal_date: "2023-12-31", progress: 0)
Goal.create(user_id: 2, target_weight: 55, goal_date: "2023-12-31", progress: 0)

# Activities
Activity.create(user_id: 1, activity: "Running", calories_burned: 500, activity_date: "2023-04-05")
Activity.create(user_id: 1, activity: "Swimming", calories_burned: 600, activity_date: "2023-04-06")
Activity.create(user_id: 2, activity: "Cycling", calories_burned: 700, activity_date: "2023-04-07")

# Consumptions
Consumption.create(user_id: 1, food_id: 1, quantity: 200, consumed_at: "2023-04-05 12:00:00")
Consumption.create(user_id: 1, food_id: 2, quantity: 100, consumed_at: "2023-04-05 18:00:00")
Consumption.create(user_id: 2, food_id: 3, quantity: 150, consumed_at: "2023-04-07 13:00:00")



