# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
# create foods
Foods.create(name: "Apple", kcal_per_g: 0.37)
Foods.create(name: "Apricot", kcal_per_g: 0.34)
Foods.create(name: "Avocado", kcal_per_g: 1.34)
Foods.create(name: "Banana", kcal_per_g: 0.51)
Foods.create(name: "Blackberries", kcal_per_g: 0.21)
Foods.create(name: "Blackcurrant", kcal_per_g: 0.24)
Foods.create(name: "Cherries", kcal_per_g: 0.36)
Foods.create(name: "Clementine", kcal_per_g: 0.39)
Foods.create(name: "Coconut (Fresh)", kcal_per_g: 3.51)
Foods.create(name: "Cranberries", kcal_per_g: 0.15)
Foods.create(name: "Cucumber", kcal_per_g: 0.15)
Foods.create(name: "Dates (Dried)", kcal_per_g: 2.27)
Foods.create(name: "Figs (Fresh)", kcal_per_g: 2.09)
Foods.create(name: "Grapefruit", kcal_per_g: 0.25)
Foods.create(name: "Kiwi", kcal_per_g: 0.42)
Foods.create(name: "Lemon", kcal_per_g: 0.15)
Foods.create(name: "Lime", kcal_per_g: 0.09)
Foods.create(name: "Lychee", kcal_per_g: 0.36)
Foods.create(name: "Mango", kcal_per_g: 0.39)
Foods.create(name: "Acorn squash", kcal_per_g: 0.4)
Foods.create(name: "Artichoke", kcal_per_g: 0.41)
Foods.create(name: "Asparagus", kcal_per_g: 0.29)
Foods.create(name: "Beetroot", kcal_per_g: 0.42)
Foods.create(name: "Broccoli", kcal_per_g: 0.35)
Foods.create(name: "Brussels Sprout", kcal_per_g: 0.51)
Foods.create(name: "Butternut squash", kcal_per_g: 0.36)
Foods.create(name: "Cabbage", kcal_per_g: 0.27)
Foods.create(name: "Carrot", kcal_per_g: 0.1)
Foods.create(name: "Cauliflower", kcal_per_g: 0.3)
Foods.create(name: "Celery", kcal_per_g: 0.08)
Foods.create(name: "Chicory", kcal_per_g: 0.11)
Foods.create(name: "Corn", kcal_per_g: 0.54)
Foods.create(name: "Edamame", kcal_per_g: 1.4)
Foods.create(name: "Green beans", kcal_per_g: 0.25)
Foods.create(name: "Iceberg lettuce", kcal_per_g: 0.1)
Foods.create(name: "Kale", kcal_per_g: 0.3)
Foods.create(name: "Leek", kcal_per_g: 0.2)
Foods.create(name: "Mushroom", kcal_per_g: 0.08)
Foods.create(name: "Onion", kcal_per_g: 0.43)
Foods.create(name: "Peas", kcal_per_g: 0.7)
Foods.create(name: "Peppers (Red)", kcal_per_g: 0.21)
Foods.create(name: "Potato", kcal_per_g: 0.97)
Foods.create(name: "Pumpkin", kcal_per_g: 0.13)
Foods.create(name: "Radish", kcal_per_g: 0.33)
Foods.create(name: "Romaine Lettuce", kcal_per_g: 0.15)
Foods.create(name: "Spinach", kcal_per_g: 0.24)
Foods.create(name: "Bean Sprouts", kcal_per_g: 0.3)
Foods.create(name: "Turnips", kcal_per_g: 0.23)
Foods.create(name: "Yam", kcal_per_g: 1.53)
Foods.create(name: "Zucchini / Courgette", calories_per_g: 0.1)
Foods.create(name: "Adzuki Beans", kcal_per_g: 0.146)
Foods.create(name: "Amaranth (Dried)", kcal_per_g: 0.359)
Foods.create(name: "Barley (Dried)", kcal_per_g: 0.31)
Foods.create(name: "Beluga Lentils", kcal_per_g: 0.094)
Foods.create(name: "Black Beans", kcal_per_g: 0.12)
Foods.create(name: "Black Eyed Peas", kcal_per_g: 0.11)
Foods.create(name: "Brown Lentils", kcal_per_g: 0.105)
Foods.create(name: "Brown Rice", kcal_per_g: 0.132)
Foods.create(name: "Buckwheat", kcal_per_g: 0.075)
Foods.create(name: "Bulgur", kcal_per_g: 0.085)
Foods.create(name: "Chickpeas", kcal_per_g: 0.128)
Foods.create(name: "Corn", kcal_per_g: 0.054)
Foods.create(name: "Green Lentils", kcal_per_g: 0.105)
Foods.create(name: "Green Peas", kcal_per_g: 0.07)
Foods.create(name: "Green Split Peas", kcal_per_g: 0.122)
Foods.create(name: "Large Fava Beans", kcal_per_g: 0.124)
Foods.create(name: "Millet", kcal_per_g: 0.199)
Foods.create(name: "Oats (Rolled)", kcal_per_g: 0.381)
Foods.create(name: "Pinto Beans", kcal_per_g: 0.137)
Foods.create(name: "Quinoa", kcal_per_g: 0.111)
Foods.create(name: "Red Kidney Beans", kcal_per_g: 0.105)
Foods.create(name: "Red Split Lentils", kcal_per_g: 0.1)
Foods.create(name: "White Rice", kcal_per_g: 0.131)
Foods.create(name: "Wild Rice", kcal_per_g: 0.15)

Foods.create(name: "Bacon (Pork)", kcal_per_g: 2.4)
Foods.create(name: "Chicken Breast", kcal_per_g: 1.48)
Foods.create(name: "Chicken Wings", kcal_per_g: 1.1)
Foods.create(name: "Chicken Thighs", kcal_per_g: 1.33)
Foods.create(name: "Chicken Eggs", kcal_per_g: 1.55)
Foods.create(name: "Duck (No Skin)", kcal_per_g: 1.95)
Foods.create(name: "Escargots", kcal_per_g: 0.9)
Foods.create(name: "Lamb", kcal_per_g: 1.22)
Foods.create(name: "Liver", kcal_per_g: 1.19)
Foods.create(name: "Sausage (Chicken)", kcal_per_g: 1.72)
Foods.create(name: "Sausage (Turkey)", kcal_per_g: 1.96)
Foods.create(name: "Sausage (Pork)", kcal_per_g: 3.18)
Foods.create(name: "Quail Eggs", kcal_per_g: 1.58)
Foods.create(name: "Turkey (Dark Meat)", kcal_per_g: 1.84)
Foodss.create(name: "Turkey (White Meat)", kcal_per_g: 1.04)
Food.create(name: "Quail Eggs", kcal_per_g: 1.58)

Foods.create(name: "Venison", kcal_per_g: 1.34)
Foods.create(name: "Ahi Tuna", kcal_per_g: 120)
Foods.create(name: "Albacore", kcal_per_g: 128)
Foods.create(name: "Catfish", kcal_per_g: 95)
Foods.create(name: "Caviar", kcal_per_g: 250)
Foods.create(name: "Crab", kcal_per_g: 87)
Foods.create(name: "Eel", kcal_per_g: 184)
Foods.create(name: "Flounder", kcal_per_g: 91)
Foods.create(name: "Grouper", kcal_per_g: 92)
Foods.create(name: "Herring", kcal_per_g: 158)
Foods.create(name: "Lobster", kcal_per_g: 90)
Foods.create(name: "Mussels", kcal_per_g: 86)
Foods.create(name: "Oysters", kcal_per_g: 81)
Foods.create(name: "Salmon", kcal_per_g: 183)
Foods.create(name: "Scallops", kcal_per_g: 88)
Foods.create(name: "Sea Bass", kcal_per_g: 97)
Foods.create(name: "Shrimp", kcal_per_g: 106)
Foods.create(name: "Smelt", kcal_per_g: 97)
Foods.create(name: "Squid", kcal_per_g: 92)
Foods.create(name: "Tilapia", kcal_per_g: 96)
Foods.create(name: "Trout", kcal_per_g: 148)
Foods.create(name: "Whitefish", kcal_per_g: 134)
Foods.create(name: "Yellowfin Tuna", kcal_per_g: 108)
Foods.create(name: "Butter", kcal_per_g: 7.16)
Foods.create(name: "Buttermilk (1%)", kcal_per_g: 0.41)
Foods.create(name: "Cheddar Cheese", kcal_per_g: 4.03)
Foods.create(name: "Cottage Cheese (1%)", kcal_per_g: 0.72)
Foods.create(name: "Cream (heavy)", kcal_per_g: 3.47)
Foods.create(name: "Cream Cheese", kcal_per_g: 2.31)
Foods.create(name: "Evaporated Milk", kcal_per_g: 1.42)
Foods.create(name: "Ghee", kcal_per_g: 8.99)
Foods.create(name: "Goat's Milk", kcal_per_g: 0.71)
Foods.create(name: "Ice Cream (Vanilla)", kcal_per_g: 2.07)
Foods.create(name: "Kefir", kcal_per_g: 0.67)
Foods.create(name: "Ricotta Cheese", kcal_per_g: 1.74)
Foods.create(name: "Skim Milk", kcal_per_g: 0.38)
Foods.create(name: "Sour Cream", kcal_per_g: 2.14)
Foods.create(name: "Soy Milk", kcal_per_g: 0.46)
Foods.create(name: "Swiss Cheese", kcal_per_g: 3.80)
Foods.create(name: "Yogurt, Whole Milk", kcal_per_g: 0.61)
Foods.create(name: "Quail Eggs", kcal_per_g: 1.58)
Foods.create(name: "Yogurt, no fat", kcal_per_g: 55)
Foods.create(name: "Whole Milk", kcal_per_g: 62)

Foods.create(name: "Bagel", kcal_per_g: 275)
Foods.create(name: "Biscuit", kcal_per_g: 300)
Foods.create(name: "Corn tortilla", kcal_per_g: 218)
Foods.create(name: "English Muffin", kcal_per_g: 235)
Foods.create(name: "Flour tortilla", kcal_per_g: 312)
Foods.create(name: "Pasta (cooked)", kcal_per_g: 158)
Foods.create(name: "Rye Bread", kcal_per_g: 258)
Foods.create(name: "Sourdough Bread", kcal_per_g: 266)
Foods.create(name: "Wheat Bread", kcal_per_g: 313)
Foods.create(name: "Whole grain pasta (cooked)", kcal_per_g: 124)

Foods.create(name: "Avocado oil", kcal_per_g: 883)
Foods.create(name: "Canola oil", kcal_per_g: 883)
Foods.create(name: "Coconut oil", kcal_per_g: 861)
Foods.create(name: "Corn oil", kcal_per_g: 857)
Foods.create(name: "Olive oil", kcal_per_g: 880)
Foods.create(name: "Peanut oil", kcal_per_g: 883)
Foods.create(name: "Safflower oil", kcal_per_g: 883)
Foods.create(name: "Soybean oil", kcal_per_g: 883)
Foods.create(name: "Sunflower oil", kcal_per_g: 883)

Foods.create(name: "Carbonated Cola", kcal_per_g: 37)
Foods.create(name: "Coffee, black", kcal_per_g: 1)
Foods.create(name: "Diet Cola", kcal_per_g: 0)
Foods.create(name: "Apple Juice (100%)", kcal_per_g: 49)
Foods.create(name: "Ginger ale", kcal_per_g: 34)
Foods.create(name: "Hot Cocoa", kcal_per_g: 81)
Foods.create(name: "Hot Tea (no sugar)", kcal_per_g: 1)
Foods.create(name: "Iced Tea (no sugar)", kcal_per_g: 1)
Foods.create(name: "Lemonade", kcal_per_g: 25)
Foods.create(name: "Sweet Iced Tea", kcal_per_g: 18)
Foods.create(name: "Tonic Water", kcal_per_g: 35)

Foods.create(name: "Light Beer", kcal_per_g: 29)
Foods.create(name: "Gin", kcal_per_g: 217)
Foods.create(name: "Lager", kcal_per_g: 43)
Foods.create(name: "Pilsner", kcal_per_g: 44)
Foods.create(name: "Porter", kcal_per_g: 45)
Foods.create(name: "Rum", kcal_per_g: 217)
Foods.create(name: "Stout", kcal_per_g: 50)
Foods.create(name: "Vodka", kcal_per_g: 217)
Foods.create(name: "Whiskey", kcal_per_g: 217)
Foods.create(name: "Wine", kcal_per_g: 83)

# Users
User.create(username: "john_doe", firstname: "John", lastname: "Doe", age: "30", email: "john@example.com", weight: 75, height: 180, password: "password", password_confirmation: "password")
User.create(username: "jane_doe", firstname: "Jane", lastname: "Doe", age: "25", email: "jane@example.com", weight: 60, height: 170, password: "password", password_confirmation: "password")

# Goals
Goal.create(user_id: 1, target_weight: 70, goal_date: "2023-12-31", progress: 0)
Goal.create(user_id: 2, target_weight: 55, goal_date: "2023-12-31", progress: 0)

# Activities
Activity.create(user_id: 1, activity: "Running", calories_burned: 500, activity_date: "2023-04-05")
Activity.create(user_id: 1, activity: "Swimming", calories_burned: 600, activity_date: "2023-04-06")
Activity.create(user_id: 2, activity: "Cycling", calories_burned: 700, activity_date: "2023-04-07")

# Consumptions
Consumption.create(user_id: 1, food_id: 1, quantity: 200, consumed_at: "2023-04-05 12:00:00")
Consumption.create(user_id: 1, food_id: 2, quantity: 100, consumed_at: "2023-04-05 18:00:00")
Consumption.create(user_id: 2, food_id: 3, quantity: 150, consumed_at: "2023-04-07 13:00:00")



